const test=require('node:test');
const assert=require('node:assert/strict');
const fs=require('node:fs');
const vm=require('node:vm');
const {stripTypeScriptTypes}=require('node:module');
const source=stripTypeScriptTypes(fs.readFileSync(require('node:path').join(__dirname,'../supabase/functions/soha-api/index.ts'),'utf8').replace(/^import .*\n/,''));
const fixed=Date.parse('2026-10-05T02:30:00Z');
class Clock extends Date {constructor(...args){super(...(args.length?args:[fixed]));}static now(){return fixed;}}
function fixture(){
 let handler,writes=0,version=1,data={staff:[{id:100,name:'강선주',active:true,home:'coex'},{id:101,name:'직원 A',active:true,home:'coex'},{id:102,name:'직원 B',active:true,home:'coex'}],sites:[{id:'coex'}],shifts:[{id:1,person:101,branch:'coex',date:'2026-10-04',start:'09:00',end:'18:00',kind:'work',overnight:false}],attendanceLogs:[{id:'other-record',person:102,branch:'coex',date:'2026-10-04',inAt:'2026-10-04T00:00:00Z',outAt:'2026-10-04T09:00:00Z'}],branchPhotos:[],requests:[],dailyLedger:[],records:[],movesLog:[],inventoryMoves:[],menuLogs:[]};
 const db={from(name){assert.equal(name,'soha_state');return {select(){return {eq(){return {single:async()=>({data:{version,payload:structuredClone(data)}})}}}}};},async rpc(name,args){if(name==='soha_identity')return {data:args.t==='master'?{person:100,mustChange:false}:args.t==='employee'?{person:101,mustChange:false}:null};assert.equal(name,'soha_write');writes++;if(args.v!==version)return {data:null};data=structuredClone(args.d);return {data:++version};}};
 vm.runInNewContext(source,{createClient:()=>db,Deno:{env:{get:()=>''},serve:fn=>handler=fn},Date:Clock,Intl,Response,Request,TextEncoder,structuredClone,crypto:globalThis.crypto,console:{error(){}}});
 return {get data(){return data;},get writes(){return writes;},async call(body,token='master'){const response=await handler(new Request('https://example.test',{method:'POST',headers:{'Content-Type':'application/json','Authorization':'Bearer '+token},body:JSON.stringify(body)}));return {status:response.status,data:await response.json()};}};
}
const entry=()=>({action:'attendance-create',id:'f19f1355-afce-4b65-b91d-8f1ed76756e3',person:101,branch:'coex',shift:1,inAt:'2026-10-04T00:15:00.000Z',outAt:'2026-10-04T09:20:00.000Z',memo:'누락 기록'});
test('only the master can manually add completed attendance',async()=>{const f=fixture();assert.equal((await f.call(entry(),'employee')).status,403);assert.equal((await f.call(entry(),'invalid')).status,401);assert.equal(f.writes,0);});
test('manual entry preserves schedules, records its author, and retries idempotently',async()=>{const f=fixture(),shifts=JSON.stringify(f.data.shifts);const result=await f.call(entry());assert.equal(result.status,200);const record=result.data.data.attendanceLogs.find(a=>a.id===entry().id);assert.equal(record.person,101);assert.equal(record.shift,1);assert.equal(record.date,'2026-10-04');assert.equal(record.manual,true);assert.equal(record.createdBy,100);assert.equal(record.inAt,entry().inAt);assert.equal(JSON.stringify(f.data.shifts),shifts);assert.equal((await f.call(entry())).status,200);assert.equal(f.writes,1);assert.equal(f.data.attendanceLogs.length,2);});
test('invalid, future, mismatched, or overlapping records never write',async()=>{for(const patch of [{inAt:'bad'},{outAt:'bad'},{outAt:'2026-10-04T00:00:00Z'},{outAt:'2026-10-06T00:00:00Z'},{shift:999},{person:102},{branch:'missing'},{id:'invalid-id'}]){const f=fixture(),result=await f.call({...entry(),...patch});assert.equal(result.status,400,JSON.stringify(patch));assert.equal(f.writes,0);}const f=fixture();await f.call(entry());const second=await f.call({...entry(),id:'5483baf2-688b-435f-920e-caa849e26f01'});assert.equal(second.status,400);assert.equal(f.writes,1);});
test('unlinked manual records still count work time and employees receive only their own history',async()=>{const f=fixture();assert.equal((await f.call({...entry(),shift:null})).status,200);const employee=await f.call({action:'get'},'employee');assert.equal(employee.status,200);assert.equal(employee.data.data.attendanceLogs.length,1);assert.ok(employee.data.data.attendanceLogs.every(a=>a.person===101));assert.equal(employee.data.data.attendanceLogs[0].shift,null);});
test('invalid checkout cannot enter attendance through a correction',async()=>{const f=fixture();const result=await f.call({action:'attendance-edit',id:'other-record',inAt:'2026-10-04T00:00:00Z',outAt:'bad'});assert.equal(result.status,400);assert.equal(f.writes,0);});
