const test=require('node:test');
const assert=require('node:assert/strict');
const fs=require('node:fs');
const vm=require('node:vm');
const {stripTypeScriptTypes}=require('node:module');
const source=stripTypeScriptTypes(fs.readFileSync(require('node:path').join(__dirname,'../supabase/functions/soha-api/index.ts'),'utf8').replace(/^import .*\n/,''));
const fixed=Date.parse('2026-10-05T02:30:00Z');
class Clock extends Date {constructor(...args){super(...(args.length?args:[fixed]));}static now(){return fixed;}}
function fixture(){
 let handler,writes=0,version=1,data={staff:[{id:100,name:'강선주',username:'owner',active:true,home:'hq',moves:[]},{id:101,name:'직원 A',username:'staff-a',active:true,home:'coex',moves:[]},{id:102,name:'직원 B',username:'staff-b',active:true,home:'coex',moves:[],bank:'private'}],sites:[{id:'hq'},{id:'coex',coords:[127.0595,37.5111],address:'확인 주소',geofenceEnabled:true,radius:100}],shifts:[{id:1,person:101,branch:'coex',date:'2026-10-05',start:'09:00',end:'18:00',kind:'work',overnight:false},{id:2,person:100,branch:'hq',date:'2026-10-05',start:'09:00',end:'18:00',kind:'work',overnight:false}],attendanceLogs:[{id:'b-record',person:102,branch:'coex',date:'2026-10-04',inAt:'2026-10-04T00:00:00Z',outAt:'2026-10-04T09:00:00Z'}],branchPhotos:[],requests:[],dailyLedger:[{id:7,branch:'coex',date:'2026-10-04',sale:1000}],records:[],movesLog:[],inventoryMoves:[],menuLogs:[]};
 const db={from(name){assert.equal(name,'soha_state');return {select(){return {eq(){return {single:async()=>({data:{version,payload:structuredClone(data)}})}}}}};},async rpc(name,args){if(name==='soha_identity')return {data:{person:{owner:100,a:101,b:102}[args.t],mustChange:false}};assert.equal(name,'soha_write');writes++;if(args.v!==version)return {data:null};data=structuredClone(args.d);return {data:++version};}};
 vm.runInNewContext(source,{createClient:()=>db,Deno:{env:{get:()=>''},serve:fn=>handler=fn},Date:Clock,Intl,Response,Request,TextEncoder,structuredClone,crypto:globalThis.crypto,console:{error(){}}});
 return {get data(){return data;},get version(){return version;},get writes(){return writes;},async call(body,token='owner'){const response=await handler(new Request('https://example.test',{method:'POST',headers:{'Content-Type':'application/json','Authorization':'Bearer '+token},body:JSON.stringify(body)}));return {status:response.status,data:await response.json()};}};
}
const position=()=>({lat:37.5111,lng:127.0595,accuracy:8,timestamp:fixed});
test('GPS punch is server validated and attributed to the logged in employee',async()=>{const f=fixture();const result=await f.call({action:'punch',kind:'in',shift:1,position:position()},'a');assert.equal(result.status,200);assert.equal(f.writes,1);const a=f.data.attendanceLogs.find(a=>a.person===101);assert.equal(a.branch,'coex');assert.equal(a.inAt,new Date(fixed).toISOString());assert.equal(a.inPosition.distance,0);assert.equal((await f.call({action:'punch',kind:'in',shift:1,position:position()},'a')).status,400);assert.equal(f.writes,1);assert.equal((await f.call({action:'punch',kind:'out',shift:1,position:position()},'a')).status,200);assert.equal(f.writes,2);});
test('outside, imprecise, stale, forged, and disabled positions do not create attendance',async()=>{for(const patch of [{lat:37.52},{accuracy:101},{timestamp:fixed-31000},{timestamp:fixed+6000},{lat:NaN},{lng:181},{accuracy:0}]){const f=fixture();assert.equal((await f.call({action:'punch',kind:'in',shift:1,position:{...position(),...patch}},'a')).status,400,JSON.stringify(patch));assert.equal(f.writes,0);}for(const patch of [{geofenceEnabled:false},{address:''},{radius:null},{coords:[null,37.5]}]){const f=fixture();Object.assign(f.data.sites[1],patch);assert.equal((await f.call({action:'punch',kind:'in',shift:1,position:position()},'a')).status,400);assert.equal(f.writes,0);}});
test('HQ and another employee schedule cannot be punched',async()=>{const f=fixture();assert.equal((await f.call({action:'punch',kind:'in',shift:2,position:position()})).status,400);assert.equal((await f.call({action:'punch',kind:'in',shift:1,position:position()})).status,400);assert.equal(f.writes,0);});
test('master grant and revocation update access while retaining the employee identity',async()=>{const f=fixture();let data=structuredClone(f.data);data.staff[1].isMaster=true;assert.equal((await f.call({action:'save',version:f.version,data})).status,200);let r=await f.call({action:'get'},'a');assert.equal(r.data.person,101);assert.equal(r.data.master,true);assert.equal(r.data.data.staff[2].bank,'private');assert.equal(r.data.data.dailyLedger.length,1);assert.equal((await f.call({action:'punch',kind:'in',shift:1,position:position()},'a')).status,200);assert.equal(f.data.attendanceLogs.at(-1).person,101);data=structuredClone(f.data);data.staff[1].isMaster=false;assert.equal((await f.call({action:'save',version:f.version,data})).status,200);r=await f.call({action:'get'},'a');assert.equal(r.data.master,false);assert.equal(r.data.data.staff[2].bank,undefined);assert.equal(r.data.data.dailyLedger.length,0);assert.ok(r.data.data.attendanceLogs.every(a=>a.person===101));});
test('employees cannot grant themselves master or modify their HQ membership',async()=>{const f=fixture(),data=(await f.call({action:'get'},'a')).data.data;data.staff.find(p=>p.id===101).isMaster=true;assert.equal((await f.call({action:'save',version:f.version,data},'a')).status,403);assert.equal(f.writes,0);delete data.staff.find(p=>p.id===101).isMaster;data.staff.find(p=>p.id===101).hqMember=true;await f.call({action:'save',version:f.version,data},'a');assert.equal(f.data.staff[1].hqMember,undefined);});
test('root and delegated masters must keep their own active master account',async()=>{for(const patch of [p=>p.isMaster=false,p=>p.active=false]){const f=fixture(),data=structuredClone(f.data);patch(data.staff[0]);assert.equal((await f.call({action:'save',version:f.version,data})).status,400);assert.equal(f.writes,0);}const f=fixture();f.data.staff[1].isMaster=true;const data=structuredClone(f.data);data.staff=data.staff.filter(p=>p.id!==101);assert.equal((await f.call({action:'save',version:f.version,data},'a')).status,400);assert.equal(f.writes,0);});
test('HQ membership coexists with store membership and duplicate usernames are rejected',async()=>{const f=fixture();let data=structuredClone(f.data);data.staff[1].hqMember=true;assert.equal((await f.call({action:'save',version:f.version,data})).status,200);assert.equal(f.data.staff[1].home,'coex');assert.equal(f.data.staff[1].hqMember,true);data=structuredClone(f.data);data.staff[2].username='STAFF-A';assert.equal((await f.call({action:'save',version:f.version,data})).status,400);assert.equal(f.writes,1);});
test('photos are available to checked in masters, one per store per day',async()=>{const f=fixture();f.data.staff[1].isMaster=true;await f.call({action:'punch',kind:'in',shift:1,position:position()},'a');const photo={branch:'coex',date:'2026-10-05',image:'data:image/jpeg;base64,AA==',...position()};assert.equal((await f.call({action:'photo',photo},'a')).status,200);assert.equal(f.data.branchPhotos[0].creator,101);assert.equal((await f.call({action:'photo',photo},'a')).status,400);assert.equal(f.writes,2);});
