import { createClient } from 'npm:@supabase/supabase-js@2';
const db=createClient(Deno.env.get('SUPABASE_URL')!,Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!,{auth:{persistSession:false}});
const headers={'Access-Control-Allow-Origin':'*','Access-Control-Allow-Headers':'authorization,apikey,content-type','Access-Control-Allow-Methods':'POST,OPTIONS','Content-Type':'application/json','Cache-Control':'no-store'};
const reply=(data:unknown,status=200)=>new Response(JSON.stringify(data),{status,headers});
const fail=(message:string,status=400)=>{throw Object.assign(new Error(message),{status});};
const today=()=>new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Seoul'}).format(new Date());
const iso=(d:string,t:string)=>new Date(`${d}T${t}:00+09:00`).getTime();
const next=(d:string)=>new Date(new Date(d+'T12:00:00+09:00').getTime()+86400000).toISOString().slice(0,10);
const end=(s:any)=>iso(s.overnight?next(s.date):s.date,s.end);
const same=(a:unknown,b:unknown)=>JSON.stringify(a)===JSON.stringify(b);
const affiliation=(p:any)=>[...(p.moves||[])].filter((x:any)=>x.date<=today()).sort((a:any,b:any)=>b.date.localeCompare(a.date))[0]?.branch||p.home;
function clean(d:any){for(const p of d.staff){delete p.password;delete p.passwordHash;delete p.passwordSalt;}d.branchPhotos=(d.branchPhotos||[]).filter((p:any)=>p.date>new Date(iso(today(),'12:00')-7*86400000).toISOString().slice(0,10));return d;}
function filtered(d:any,pid:number){const out=structuredClone(d);clean(out);if(pid===100)return out;out.staff=out.staff.filter((p:any)=>p.active||p.id===pid).map((p:any)=>p.id===pid?p:{id:p.id,name:p.name,phone:p.phone,role:p.role,job:p.job,home:p.home,moves:p.moves,active:p.active,avatarSlot:p.avatarSlot,example:p.example});out.dailyLedger=[];out.records=[];out.attendanceLogs=out.attendanceLogs.filter((a:any)=>a.person===pid);out.requests=(out.requests||[]).filter((r:any)=>r.person===pid);out.movesLog=[];const p=d.staff.find((x:any)=>x.id===pid),branches=new Set([affiliation(p),...d.shifts.filter((s:any)=>s.person===pid&&s.date===today()).map((s:any)=>s.branch)]);out.inventoryMoves=out.inventoryMoves.filter((r:any)=>branches.has(r.branch));out.menuLogs=out.menuLogs.filter((r:any)=>branches.has(r.branch));out.branchPhotos=out.branchPhotos.filter((r:any)=>branches.has(r.branch));return out;}
function validShift(d:any,s:any,oldId?:number){if(!s||!d.staff.some((p:any)=>p.id===s.person&&p.active)||!d.sites.some((b:any)=>b.id===s.branch)||!/^\d{4}-\d{2}-\d{2}$/.test(s.date)||s.date<today())fail('과거 근무 일정은 수정할 수 없습니다.');if(!['work','off','leave','training'].includes(s.kind))fail('일정 구분을 확인하세요.');if(['off','leave'].includes(s.kind))return;if(!/^\d{2}:(00|30)$/.test(s.start)||!/^\d{2}:(00|30)$/.test(s.end)||!Number.isFinite(end(s))||end(s)<=iso(s.date,s.start)||end(s)-iso(s.date,s.start)>24*3600000)fail('출퇴근 시간은 30분 단위이며 24시간 이내여야 합니다.');if(d.shifts.some((x:any)=>x.id!==oldId&&x.person===s.person&&!x.pending&&!['off','leave'].includes(x.kind)&&Math.max(iso(x.date,x.start),iso(s.date,s.start))<Math.min(end(x),end(s))))fail('같은 직원의 근무시간이 겹칩니다.');}
function validateGeo(b:any,pos:any){if(!b?.geofenceEnabled||!b.address||!b.coords)fail('점포의 현장 위치 인증 설정을 먼저 확인하세요.');if(!pos||![pos.lat,pos.lng,pos.accuracy,pos.timestamp].every(Number.isFinite)||pos.accuracy<=0||Math.abs(Date.now()-pos.timestamp)>60000)fail('최신 위치 정보가 필요합니다.');const rad=(x:number)=>x*Math.PI/180,dy=rad(pos.lat-b.coords[1]),dx=rad(pos.lng-b.coords[0]),a=Math.sin(dy/2)**2+Math.cos(rad(pos.lat))*Math.cos(rad(b.coords[1]))*Math.sin(dx/2)**2,distance=6371000*2*Math.atan2(Math.sqrt(a),Math.sqrt(1-a));if(distance+pos.accuracy>b.radius)fail('점포 반경 내 위치가 확인되지 않았습니다.');return {...pos,distance};}
Deno.serve(async req=>{if(req.method==='OPTIONS')return new Response('ok',{headers});if(req.method!=='POST')return reply({error:'POST required'},405);try{if(Number(req.headers.get('content-length'))>2500000)fail('파일이 너무 큽니다.');const x=await req.json(),action=x.action;const token=(req.headers.get('authorization')||'').replace(/^Bearer /,'');if(action==='login'){if(typeof x.username!=='string'||typeof x.password!=='string'||x.username.length>80||x.password.length>128)fail('아이디와 비밀번호를 확인하세요.');const {data,error}=await db.rpc('soha_login',{u:x.username.trim(),p:x.password,ip:req.headers.get('x-forwarded-for')?.split(',')[0]||'unknown'});if(error)throw error;if(data?.error)return reply(data,401);return reply(data);}
const {data:identity,error:identityError}=await db.rpc('soha_identity',{t:token});if(identityError||!identity)fail('로그인이 만료되었습니다. 다시 로그인하세요.',401);const pid=Number(identity.person),master=pid===100;
if(action==='logout'){await db.from('soha_sessions').delete().eq('token_hash',Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(token)))).map(x=>x.toString(16).padStart(2,'0')).join(''));return reply({ok:true});}
if(action==='password'){if(typeof x.password!=='string'||x.password.length<8||x.password.length>128)fail('새 비밀번호는 8~128자로 입력하세요.');const {data,error}=await db.rpc('soha_password',{t:token,p:x.password});if(error||!data)fail('비밀번호를 변경하지 못했습니다.');return reply({ok:true});}
if(identity.mustChange) return reply({person:pid,mustChange:true});
for(let attempt=0;attempt<3;attempt++){const {data:row,error}=await db.from('soha_state').select('version,payload').eq('id',true).single();if(error)throw error;const d=clean(row.payload),p=d.staff.find((s:any)=>s.id===pid);if(!p?.active)fail('사용 가능한 계정이 아닙니다.',401);
if(action==='get')return reply({version:row.version,person:pid,mustChange:false,data:filtered(d,pid)});
if(action==='save'){if(x.version!==row.version)fail('다른 변경이 먼저 저장됐습니다. 새로고침 후 다시 수정하세요.',409);if(!x.data||!Array.isArray(x.data.staff)||!Array.isArray(x.data.shifts))fail('저장 형식을 확인하세요.');if(master){const n=clean(x.data);for(const s of d.shifts.filter((s:any)=>s.date<today()))if(!same(s,n.shifts.find((v:any)=>v.id===s.id)))fail('과거 근무 일정은 수정할 수 없습니다.');for(const s of n.shifts.filter((s:any)=>s.date<today()))if(!d.shifts.some((v:any)=>v.id===s.id))fail('과거 근무 일정은 등록할 수 없습니다.');for(const s of n.shifts.filter((s:any)=>s.date>=today()))if(!same(s,d.shifts.find((v:any)=>v.id===s.id)))validShift(n,s,s.id);if(!n.staff.some((s:any)=>s.id===100&&s.name==='강선주'&&s.active))fail('마스터 강선주 계정을 유지해야 합니다.');n.requests=d.requests;n.attendanceLogs=d.attendanceLogs;n.branchPhotos=d.branchPhotos;Object.assign(d,n);}else{const branches=new Set([affiliation(p),...d.shifts.filter((s:any)=>s.person===pid&&s.date===today()).map((s:any)=>s.branch)]);for(const key of ['inventoryMoves','menuLogs']){const incoming=x.data[key]||[],old=d[key];for(const r of incoming){const existing=old.find((v:any)=>v.id===r.id);if(same(r,existing))continue;if(!branches.has(r.branch)||existing&&existing.creator!==pid)fail('본인의 점포 내역만 수정할 수 있습니다.',403);if(typeof r.date!=='string'||r.date>today()||!Number.isFinite(r.qty??r.sold)||Math.min(r.qty??r.sold, r.amount??0)<0)fail('수량과 날짜를 확인하세요.');r.creator=pid;r.createdBy=p.name;r.updatedAt=new Date().toISOString();if(existing)old[old.indexOf(existing)]=r;else old.push(r);}}} }
else if(action==='settings'){const allowed=['phone','email','bank','address','birthday','healthStatus','healthIssued','healthDue','avatarSlot'];for(const k of allowed)if(k in x.profile){if(k==='avatarSlot'){if(!Number.isInteger(x.profile[k])||x.profile[k]<0||x.profile[k]>8)fail('캐릭터를 확인하세요.');}else if(typeof x.profile[k]!=='string'||x.profile[k].length>300)fail('개인정보 입력을 확인하세요.');p[k]=x.profile[k];}}
else if(action==='request'){const type=x.type,note=String(x.note||'').trim();if(!note||note.length>500)fail('수정 요청 사유를 입력하세요.');if(!['schedule','attendance'].includes(type))fail('요청 종류를 확인하세요.');if(type==='schedule'){const old=d.shifts.find((s:any)=>s.id===x.target);if(old&&(old.person!==pid||old.date<today()))fail('본인의 오늘 이후 일정만 요청할 수 있습니다.');validShift(d,{...x.patch,person:pid},old?.id);}else{const old=d.attendanceLogs.find((a:any)=>a.id===x.target);if(!old||old.person!==pid)fail('본인의 출퇴근 기록만 요청할 수 있습니다.');if(!Number.isFinite(Date.parse(x.patch.inAt))||x.patch.outAt&&(!Number.isFinite(Date.parse(x.patch.outAt))||Date.parse(x.patch.outAt)<=Date.parse(x.patch.inAt)))fail('출퇴근 시간을 확인하세요.');}d.requests=d.requests||[];d.requests.push({id:crypto.randomUUID(),person:pid,type,target:x.target||null,patch:x.patch,note,status:'pending',createdAt:new Date().toISOString()});}
else if(action==='review'){if(!master)fail('마스터만 승인할 수 있습니다.',403);const r=d.requests?.find((r:any)=>r.id===x.id&&r.status==='pending');if(!r)fail('이미 처리된 요청입니다.');if(x.approve){if(r.type==='schedule'){const old=d.shifts.find((s:any)=>s.id===r.target);if(old&&old.date<today())fail('과거 일정이 되어 승인할 수 없습니다. 반려해 주세요.');const s={...r.patch,person:r.person,id:old?.id||Math.max(0,...d.shifts.map((s:any)=>s.id))+1,pending:false,source:'승인 일정'};validShift(d,s,old?.id);if(old)d.shifts[d.shifts.indexOf(old)]=s;else d.shifts.push(s);}else{const old=d.attendanceLogs.find((a:any)=>a.id===r.target);if(!old)fail('원래 출퇴근 기록이 없습니다.');Object.assign(old,{inAt:r.patch.inAt,outAt:r.patch.outAt||null,correctedAt:new Date().toISOString(),correctedBy:pid});}r.status='approved';}else{if(!String(x.reason||'').trim())fail('반려 이유를 입력하세요.');r.status='rejected';r.reason=String(x.reason).slice(0,500);}r.reviewedAt=new Date().toISOString();}
else if(action==='attendance-create'){
 if(!master)fail('마스터만 출퇴근 이력을 추가할 수 있습니다.',403);
 const id=String(x.id||''),person=Number(x.person),branch=String(x.branch||''),start=Date.parse(x.inAt),finish=Date.parse(x.outAt);
 if(!/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i.test(id)||!d.staff.some((s:any)=>s.id===person)||!d.sites.some((s:any)=>s.id===branch))fail('직원과 점포를 확인하세요.');
 if(typeof x.inAt!=='string'||typeof x.outAt!=='string'||!Number.isFinite(start)||!Number.isFinite(finish)||finish<=start||finish>Date.now()+60000)fail('완료된 출퇴근 시간을 확인하세요.');
 const inAt=new Date(start).toISOString(),outAt=new Date(finish).toISOString(),day=new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Seoul'}).format(new Date(start));
 const shift=x.shift==null?null:d.shifts.find((s:any)=>s.id===Number(x.shift));
 if(x.shift!=null&&(!shift||shift.person!==person||shift.branch!==branch||shift.pending||['off','leave'].includes(shift.kind)||!(shift.date===day||shift.overnight&&next(shift.date)===day)))fail('선택한 직원·점포·날짜의 근무 일정을 선택하세요.');
 const existing=d.attendanceLogs.find((a:any)=>a.id===id);
 if(existing){if(existing.manual&&existing.createdBy===pid&&existing.person===person&&existing.branch===branch&&existing.shift===(shift?.id||null)&&existing.inAt===inAt&&existing.outAt===outAt)return reply({version:row.version,person:pid,data:filtered(d,pid)});fail('이미 등록된 출퇴근 기록입니다.',409);}
 if(d.attendanceLogs.some((a:any)=>a.person===person&&Math.max(start,Date.parse(a.inAt))<Math.min(finish,a.outAt?Date.parse(a.outAt):Infinity)))fail('기존 출퇴근 기록과 시간이 겹칩니다.');
 d.attendanceLogs.push({id,person,branch,shift:shift?.id||null,date:shift?.date||day,inAt,outAt,manual:true,createdBy:pid,createdAt:new Date().toISOString(),memo:String(x.memo||'').slice(0,500)});
}
else if(action==='attendance-edit'){if(!master)fail('마스터만 수정할 수 있습니다.',403);const a=d.attendanceLogs.find((a:any)=>a.id===x.id);if(!a||!Number.isFinite(Date.parse(x.inAt))||x.outAt&&(!Number.isFinite(Date.parse(x.outAt))||Date.parse(x.outAt)<=Date.parse(x.inAt)))fail('출퇴근 시간을 확인하세요.');Object.assign(a,{inAt:x.inAt,outAt:x.outAt||null,date:a.shift?a.date:new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Seoul'}).format(new Date(x.inAt)),correctedAt:new Date().toISOString(),correctedBy:pid});}
else if(action==='punch'){const open=d.attendanceLogs.find((a:any)=>a.person===pid&&!a.outAt),s=d.shifts.find((s:any)=>s.id===(open?.shift||x.shift)&&s.person===pid);if(!s||s.pending||['off','leave'].includes(s.kind)||x.kind==='in'&&(open||d.attendanceLogs.some((a:any)=>a.person===pid&&a.shift===s.id)||s.date!==today()||Date.now()<iso(s.date,s.start)-3*3600000||Date.now()>end(s)+4*3600000)||x.kind==='out'&&!open)fail('출퇴근 대상 일정을 확인하세요.');const pos=validateGeo(d.sites.find((b:any)=>b.id===s.branch),x.position),at=new Date().toISOString();if(x.kind==='in')d.attendanceLogs.push({id:crypto.randomUUID(),person:pid,branch:s.branch,shift:s.id,date:s.date,inAt:at,inPosition:pos,inDistance:pos.distance,inAccuracy:pos.accuracy});else Object.assign(open,{outAt:at,outPosition:pos,outDistance:pos.distance,outAccuracy:pos.accuracy});}
else if(action==='photo'){const open=d.attendanceLogs.find((a:any)=>a.person===pid&&!a.outAt&&a.branch===x.photo?.branch);if(!open||x.photo.date!==today()||typeof x.photo.image!=='string'||x.photo.image.length>500000||!/^data:image\/jpeg;base64,[A-Za-z0-9+/=]+$/.test(x.photo.image))fail('현재 근무 점포의 촬영 사진이 필요합니다.');if(d.branchPhotos.some((a:any)=>a.branch===open.branch&&a.date===today()))fail('오늘 점포 사진 인증이 완료됐습니다.');const pos=validateGeo(d.sites.find((b:any)=>b.id===open.branch),x.photo);d.branchPhotos.push({...x.photo,id:crypto.randomUUID(),by:p.name,creator:pid,takenAt:new Date().toISOString(),distance:pos.distance});}
else fail('지원하지 않는 작업입니다.');
const {data:nv,error:writeError}=await db.rpc('soha_write',{v:row.version,d});if(writeError)throw writeError;if(nv)return reply({version:nv,person:pid,data:filtered(d,pid)});if(action==='save')fail('동시 변경이 있습니다. 새로고침 후 다시 시도하세요.',409);
}fail('동시 저장 중입니다. 잠시 후 다시 시도하세요.',409);
}catch(e){console.error('soha-api',e.message);return reply({error:e.status?e.message:'처리하지 못했습니다. 잠시 후 다시 시도하세요.'},e.status||500);}});
